#! /bin/bash

#PATH TO DATABASE FOLDER
export PGFOLDER=/tmp/$LOGNAME

#PATH TO DATA FOLDER
export PGDATA=$PGFOLDER/myDB/data

#DATABASE LISTENING PORT
export PGPORT=$1

#DBNAME
export DBNAME=myDB

dropdb -h 127.0.0.1 -p $PGPORT $DBNAME
createdb -h 127.0.0.1 -p $PGPORT $DBNAME
